name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main # or your deploy branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.15.0"

      - name: Install dependencies
        run: npm ci

      - name: Debug Environment Variable (keep this for now, it's good confirmation)
        run: |
          echo "Value of VITE_API_BASE_URL_PROD from secrets: ${{ secrets.VITE_API_BASE_URL_PROD }}"
          echo "Value of VITE_API_BASE_URL in this context: $VITE_API_BASE_URL"
        env:
          VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL_PROD }}

      - name: Clean build artifacts and cache
        run: |
          rm -rf dist
          rm -rf node_modules/.vite # This specifically targets Vite's cache
          npm cache clean --force # npm's cache

      - name: Build Vite app
        run: npm run build
        env:
          VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL_PROD }} # Ensure it's still here!

      - name: Deploy to Azure Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN}}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          api_location: ""
          output_location: "dist"
